<a href="https://colab.research.google.com/github/NidhiSingh25901/DeepLearningWithPytorchFundamentals/blob/main/PytorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

List


In [ ]:
my_list =[[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Numpy Arrays

In [ ]:
np1 = np.random.rand(3,4)
np1
np1.dtype

dtype('float64')

Tensors

In [ ]:
tensors_2d = torch.randn(3,4)
tensors_2d

tensor([[-1.0959, -0.3959,  0.9602, -0.1197],
        [ 0.6209, -1.5628, -0.1600, -0.4268],
        [-1.1607, -1.5353,  0.6905, -0.4442]])

Tensors Operations

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mytorch2 = my_torch2.reshape(2,-1)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
mytorch2 = my_torch2.reshape(10)
mytorch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mytorch = my_torch2.reshape(2,5)
mytorch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Tensor Math Operations -  
Add, Subtract, Multiple, Divide, Remainder and Exponents
Shorthand and Longhand
Reassignment

In [1]:
import torch
import numpy as p
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_sum = tensor_a + tensor_b
tensor_sum

tensor([ 6,  8, 10, 12])

In [2]:
tensor_diff = tensor_a - tensor_b
tensor_diff

tensor([-4, -4, -4, -4])

In [3]:
tensor_mul =  tensor_a * tensor_b
tensor_mul

tensor([ 5, 12, 21, 32])

In [4]:
tensor_divide = tensor_a / tensor_b
tensor_divide

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [5]:
tensor_exp = tensor_a // tensor_b
tensor_exp

tensor([0, 0, 0, 0])

In [6]:
tensor_mod = tensor_a % tensor_b
tensor_mod

tensor([1, 2, 3, 4])

In [7]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
tensor_a.sub(tensor_b)

tensor([-4, -4, -4, -4])

In [9]:
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
tensor_a.div(tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [11]:
tensor_a.remainder(tensor_b)

tensor([1, 2, 3, 4])